
import Foundation

public enum NotionNodes {
    public static let results = "results"
    public static let properties = "properties"
    public static let title = "title"
    public static let plainText = "plain_text"
    public static let richText = "rich_text"
    public static let select = "select"
    public static let name = "name"
    public static let checkbox = "checkbox"
    public static let formula = "formula"
    public static let boolean = "boolean"
    public static let rollup = "rollup"
    public static let number = "number"
    public static let multiSelect = "multi_select"
    public static let date = "date"
    public static let start = "start"
    public static let end = "end"
    public static let relation = "relation"
    public static let id = "id"
    public static let object = "object"
    public static let status = "status"
    public static let code = "code"
    public static let message = "message"
    public static let people = "people"
    public static let createdTime = "created_time"
    public static let lastEditedTime = "last_edited_time"
    public static let createdBy = "created_by"
    public static let lastEditedBy = "last_edited_by"
    public static let url = "url"
    public static let email = "email"
    public static let phone = "phone_number"
    public static let files = "files"
    public static let file = "file"
    public static let external = "external"
    public static let startCursor = "start_cursor"
    public static let nextCursor = "next_cursor"
    public static let array = "array"
    public static let string = "string"
    public static let icon = "icon"
    public static let emoji = "emoji"
    public static let href = "href"
    public static let isEmpty = "is_empty"
    public static let isNotEmpty = "is_not_empty"
    public static let cover = "cover"
    public static let childPage = "child_page"
}
