
import Foundation

enum NotionNodes {
    static let results = "results"
    static let properties = "properties"
    static let title = "title"
    static let plainText = "plain_text"
    static let richText = "rich_text"
    static let select = "select"
    static let name = "name"
    static let checkbox = "checkbox"
    static let formula = "formula"
    static let boolean = "boolean"
    static let rollup = "rollup"
    static let number = "number"
    static let multiSelect = "multi_select"
    static let date = "date"
    static let start = "start"
    static let end = "end"
    static let relation = "relation"
    static let id = "id"
    static let object = "object"
    static let status = "status"
    static let code = "code"
    static let message = "message"
    static let people = "people"
    static let createdTime = "created_time"
    static let lastEditedTime = "last_edited_time"
    static let createdBy = "created_by"
    static let lastEditedBy = "last_edited_by"
    static let url = "url"
    static let email = "email"
    static let phone = "phone_number"
    static let files = "files"
    static let file = "file"
    static let external = "external"
}
